version: '3.8'

networks:
  custom-network:  # Define a custom network
    driver: bridge

services:
  ollama:
    # build: ./docker/ollama
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - /Users/jakewalden/.ollama:/root/.ollama:ro
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODEL=llama3.2  # Default model to use (can be any model you want)
    networks:
      - custom-network

  slack-bot:
    build: ./
    image: slack-bot
    ports:
      - "5000:5000"
    networks:
      - custom-network      